# Generated by Django 4.2.6 on 2023-12-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakDancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stagenickname_name', models.CharField(max_length=33, null=True)),
                ('whole_name', models.CharField(max_length=43, null=True)),
                ('age', models.IntegerField(null=True)),
                ('phone', models.IntegerField(blank=True, max_length=17)),
                ('email', models.EmailField(blank=True, max_length=35)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NBAplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jerseynum_number', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=33, null=True)),
                ('last_name', models.CharField(max_length=43, null=True)),
                ('age', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rappers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stagenickname_name', models.CharField(max_length=33, null=True)),
                ('whole_name', models.CharField(max_length=43, null=True)),
                ('age', models.IntegerField(null=True)),
                ('phone', models.IntegerField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=35)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tiktoker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktokeruser_name', models.CharField(max_length=23, null=True)),
                ('first_name', models.CharField(max_length=23, null=True)),
                ('last_name', models.CharField(max_length=23, null=True)),
                ('age', models.IntegerField(null=True)),
                ('phone', models.IntegerField(blank=True, max_length=19)),
                ('email', models.EmailField(blank=True, max_length=33)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='barista',
            name='name',
        ),
        migrations.AddField(
            model_name='barista',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='barista',
            name='first_name',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='barista',
            name='last_name',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='barista',
            name='email',
            field=models.EmailField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='barista',
            name='phone',
            field=models.IntegerField(blank=True, max_length=15),
        ),
    ]
