# Generated by Django 4.2.6 on 2023-12-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_breakdancer_nbaplayer_rappers_tiktoker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barista',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='breakdancer',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rappers',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktoker',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
