# Generated by Django 4.2.6 on 2023-12-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_barista_phone_alter_breakdancer_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakdancer',
            old_name='Stagenickname_name',
            new_name='stage_name',
        ),
        migrations.RenameField(
            model_name='nbaplayer',
            old_name='jerseynum_number',
            new_name='jersey_number',
        ),
        migrations.RenameField(
            model_name='rappers',
            old_name='Stagenickname_name',
            new_name='stage_name',
        ),
        migrations.RenameField(
            model_name='tiktoker',
            old_name='tiktokeruser_name',
            new_name='tiktoker_user',
        ),
    ]
