# Generated by Django 4.2.6 on 2023-12-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_stagenickname_name_breakdancer_stage_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rappers',
            new_name='Rapper',
        ),
    ]
