# Generated by Django 4.2.6 on 2023-12-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_rappers_rapper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barista',
            name='phone',
            field=models.IntegerField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='breakdancer',
            name='phone',
            field=models.IntegerField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='rapper',
            name='phone',
            field=models.IntegerField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='tiktoker',
            name='phone',
            field=models.IntegerField(blank=True, max_length=13),
        ),
    ]
