# Generated by Django 4.2.6 on 2023-12-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_barista_phone_alter_breakdancer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdancer',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='rapper',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='tiktoker',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
